const Data = {
  employees: [
    {
      name: 'Lenovo',
      Id: 101,
      category: 'Laptop',
      Amount: 20000,
      image: '/images/38960.jpg',
      Manifactured:'USA',
    },
    {
      name: 'HP',
      Id: 102,
      category: 'Salesforce develpoer',
      salary: 35000,
      image: '/images/38960.jpg',
      Experience: 3,
    },
    {
      name: 'Dell',
      Id: 103,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
    {
      name: 'Acer',
      Id: 104,
      category: 'Full Stack develpoer',
      salary: 20000,
      image: '/images/38960.jpg',
      Experience: 4,
    },
  ],
};

export default Data;
